IconText props
gnosis/safe-react-components pull request #113
Opened 2021-03-30 18:47 UTC by alongoni

Related to #109

2021-03-30 18:53 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr113--safereactcomponents.review.gnosisdev.com

2021-03-30 18:57 UTC, nicosampler commented on src/dataDisplay/IconText/index.tsx
> +  icon?: 'left' | 'right';
I would call it side or IconSide

2021-04-08 16:09 UTC, nicosampler commented on src/dataDisplay/IconText/index.tsx
> +    margin: 0 ${({ theme, margin }) => theme.margin[margin]};
This code has a problem, it's applying margin in both, right and left.
I think this should work like so: 
- if `side` is left, add right-margin
- if `side` is right add left-margin.

2021-04-08 16:10 UTC, nicosampler requested changes
There is a problem with the margins
![image](https://user-images.githubusercontent.com/4376509/114060506-d3f67880-986b-11eb-9c2f-5dfbbf1e6aca.png)

2021-04-09 08:56 UTC, katspaugh commented
@alongoni as per the retro discussion, could you add a short summary in the PR description?
What has been done, and how to test it (which icons in the UI were affected specifically).

2021-04-09 13:31 UTC, katspaugh commented
Shouldn't `margin` automatically appear in the list of props in the storybook?
I can see `iconSide` in the list but not `margin`. 🤔

2021-04-09 14:00 UTC, nicosampler commented
@katspaugh seems like a problem with the last build. Running it locally works as expected.
![Uploading image.png…]()

2021-04-09 14:46 UTC, nicosampler commented
@alongoni you can run this command `yarn tsc` to see all the places that are broken

2021-04-09 17:06 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr113--safereactcomponents.review.gnosisdev.com

2021-04-09 17:30 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr113--safereactcomponents.review.gnosisdev.com

2021-04-10 08:17 UTC, katspaugh commented
Looks good!

Maybe we could make the default margin value depend on the text size? If the text is small, the margin should be also small. And vice versa. Then you wouldn't have to pass it every time.

2021-04-12 07:13 UTC, katspaugh approved these changes

2021-04-14 15:03 UTC, dasanra approved these changes

2021-04-14 19:12 UTC, merged