(Feature) - Refactor ethScan buttons usage
gnosis/safe-react-components pull request #69
Opened 2020-10-01 13:17 UTC by Agupane

Related to [#1417](https://github.com/gnosis/safe-react/issues/1417)

2020-10-01 13:23 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr69--safereactcomponents.review.gnosisdev.com

2020-10-02 15:39 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr69--safereactcomponents.review.gnosisdev.com

2020-10-02 15:42 UTC, Agupane commented
I think we should rename `EtherscanButton` with another name like `ScanBlockButton` or something like that, what do you think/suggest? @fernandomg @nicosampler

2020-10-02 15:57 UTC, nicosampler commented
> I think we should rename `EtherscanButton` with another name like `ScanBlockButton` or something like that, what do you think/suggest? @fernandomg @nicosampler

explorerButton?

2020-10-06 14:14 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr69--safereactcomponents.review.gnosisdev.com

2020-10-06 15:02 UTC, nicosampler requested changes

2020-10-06 15:02 UTC, nicosampler commented on src/ethereum/ScanBlockButton/index.stories.tsx
> +  alt: `Show details on Etherscan`,
Can we use a different alt and URL from `explorerUrl1`?

2020-10-06 15:02 UTC, nicosampler commented on src/ethereum/ScanBlockButton/index.tsx
> +const ScanBlockButton = ({
can you rename it to be consistent with the file name?

2020-10-06 15:13 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr69--safereactcomponents.review.gnosisdev.com

2020-10-06 15:19 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr69--safereactcomponents.review.gnosisdev.com

2020-10-06 15:24 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr69--safereactcomponents.review.gnosisdev.com

2020-10-06 15:32 UTC, nicosampler approved these changes

2020-10-06 15:35 UTC, merged